// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyTY_2ocuXNP6nuNT4boDCNEe8-YA72Lc',
    appId: '1:732202326990:web:092e24079f10ec875de99f',
    messagingSenderId: '732202326990',
    projectId: 'gps-location-check',
    authDomain: 'gps-location-check.firebaseapp.com',
    storageBucket: 'gps-location-check.appspot.com',
    measurementId: 'G-1VZJJGXB02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBelGPy0TmQxvqHLRCRPvouj6wDFk02Sys',
    appId: '1:732202326990:android:4289b46b39fb46155de99f',
    messagingSenderId: '732202326990',
    projectId: 'gps-location-check',
    storageBucket: 'gps-location-check.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyTY_2ocuXNP6nuNT4boDCNEe8-YA72Lc',
    appId: '1:732202326990:web:b1db3e9bfc7a9e585de99f',
    messagingSenderId: '732202326990',
    projectId: 'gps-location-check',
    authDomain: 'gps-location-check.firebaseapp.com',
    storageBucket: 'gps-location-check.appspot.com',
    measurementId: 'G-B7N0PSK68B',
  );
}
